"""make risk profile flag optional

Revision ID: 00f06e5b0f67
Revises: c09b2ba29df0
Create Date: 2024-06-09 16:35:21.569481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00f06e5b0f67'
down_revision = 'c09b2ba29df0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portfolios', 'is_risk_taker',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('portfolios', 'is_risk_taker',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
