"""update field types and dependencies

Revision ID: 13da1bec29e8
Revises: 805dd5ebe3da
Create Date: 2024-06-15 11:33:42.319331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13da1bec29e8'
down_revision = '805dd5ebe3da'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instrument_kpi_token_metrics', 'holders',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('instrument_kpi_token_metrics', 'risk_score',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('instrument_kpi_token_metrics', 'number_markets',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instrument_kpi_token_metrics', 'number_markets',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('instrument_kpi_token_metrics', 'risk_score',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('instrument_kpi_token_metrics', 'holders',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    # ### end Alembic commands ###
