"""Add XP models

Revision ID: 1bef3df6cfbe
Revises: f6ad92bdd908
Create Date: 2023-02-12 16:15:56.880937

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bef3df6cfbe'
down_revision = 'f6ad92bdd908'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xp_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False, comment='How much is credited/debited'),
    sa.Column('reason', sa.String(), nullable=False, comment='Reason identifier'),
    sa.Column('detail', sa.String(), nullable=True, comment='Additional information'),
    sa.Column('date_credited', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('quiz_answers', 'is_correct',
               existing_type=sa.INTEGER(),
               comment='',
               existing_nullable=False)
    op.alter_column('skill_groups', 'group_key',
               existing_type=sa.VARCHAR(),
               comment='',
               existing_nullable=False)
    op.add_column('users', sa.Column('xp_total', sa.Integer(), server_default='0', nullable=False))
    op.add_column('users', sa.Column('xp_current_week', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'xp_current_week')
    op.drop_column('users', 'xp_total')
    op.alter_column('skill_groups', 'group_key',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('quiz_answers', 'is_correct',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.drop_table('xp_transactions')
    # ### end Alembic commands ###
