"""price history

Revision ID: 24d8942aea6d
Revises: a362e86f6ada
Create Date: 2022-07-12 08:03:27.467229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24d8942aea6d'
down_revision = 'a362e86f6ada'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument_kpi_price_history',
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False, comment='e.g. 1DAY, 1WEEK, 1MONTH, 1YEAR'),
    sa.Column('date_as_of', sa.DateTime(timezone=True), nullable=False, comment='date corresponding to the price'),
    sa.Column('price_open', sa.Float(), nullable=False),
    sa.Column('price_high', sa.Float(), nullable=False),
    sa.Column('price_low', sa.Float(), nullable=False),
    sa.Column('price_close', sa.Float(), nullable=False),
    sa.Column('transaction_volume', sa.Float(), nullable=False),
    sa.Column('date_last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('instrument_id', 'timeframe', 'date_as_of')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instrument_kpi_price_history')
    # ### end Alembic commands ###
