"""extend latest price model with 1-day change

Revision ID: 29963467f758
Revises: 8c04af09b2e8
Create Date: 2023-05-20 20:53:19.256697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29963467f758'
down_revision = '8c04af09b2e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instrument_kpi_latest_prices', sa.Column('change_perc_1d', sa.Float(), server_default='0', nullable=False))
    op.add_column('instrument_kpi_latest_prices', sa.Column('change_abs_1d', sa.Float(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instrument_kpi_latest_prices', 'change_abs_1d')
    op.drop_column('instrument_kpi_latest_prices', 'change_perc_1d')
    # ### end Alembic commands ###
