"""user_quiz_answers changes

Revision ID: 31fad21ea6a0
Revises: e1d7c92775ab
Create Date: 2022-10-21 12:12:28.995861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31fad21ea6a0'
down_revision = 'e1d7c92775ab'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_quiz_answers', sa.Column('id', sa.Integer(), nullable=False))
    op.drop_constraint('user_quiz_answers_pkey', 'user_quiz_answers', type_='primary')
    op.create_primary_key('user_quiz_answers_pkey', 'user_quiz_answers', ['id'])
    op.alter_column('quiz_answers', 'is_correct',
               existing_type=sa.INTEGER(),
               comment='',
               existing_nullable=False)
    op.alter_column('skill_groups', 'group_key',
               existing_type=sa.VARCHAR(),
               comment='',
               existing_nullable=False)
    
    op.alter_column('user_quiz_answers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('user_quiz_answers', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_quiz_answers', 'question_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('user_quiz_answers', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('PRIMARY', 'user_quiz_answers', type_='primary')
    op.drop_column('user_quiz_answers', 'id')
    op.create_primary_key('user_quiz_answers_pkey', 'user_quiz_answers', ['user_id', 'question_id', 'answer_id'])
    op.alter_column('skill_groups', 'group_key',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('quiz_answers', 'is_correct',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    # ### end Alembic commands ###
