"""Add last_seen user attributes

Revision ID: 32ac5b94ef75
Revises: 6c63a531ea93
Create Date: 2023-09-02 19:16:15.800591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32ac5b94ef75'
down_revision = '6c63a531ea93'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen_app_version', sa.String(), nullable=True))
    op.add_column('users', sa.Column('last_seen_platform', sa.String(), nullable=True, comment='ios/android'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen_platform')
    op.drop_column('users', 'last_seen_app_version')
    # ### end Alembic commands ###
