"""Add ex_avg_price to PortfolioTransaction

Revision ID: 4312719407a2
Revises: 1bef3df6cfbe
Create Date: 2023-02-14 18:39:40.082099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4312719407a2'
down_revision = '1bef3df6cfbe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_transactions', sa.Column('ex_avg_price', sa.String(), nullable=True, comment='Average price of the holding BEFORE the transaction has been executed'))
    op.alter_column('quiz_answers', 'is_correct',
               existing_type=sa.INTEGER(),
               comment='',
               existing_nullable=False)
    op.alter_column('skill_groups', 'group_key',
               existing_type=sa.VARCHAR(),
               comment='',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skill_groups', 'group_key',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('quiz_answers', 'is_correct',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.drop_column('portfolio_transactions', 'ex_avg_price')
    # ### end Alembic commands ###
