"""add XP seasons and XP snapshot

Revision ID: 47168a09b0b0
Revises: a7a701495247
Create Date: 2024-08-20 12:17:32.587021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47168a09b0b0'
down_revision = 'a7a701495247'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('xp_snapshot',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(), nullable=False, comment='e.g. 1W, 2W, 1M'),
    sa.Column('date_as_of', sa.DateTime(timezone=True), nullable=False, comment='when the snapshot was taken'),
    sa.Column('xp_collected', sa.Integer(), nullable=False, comment='XP collected in each period'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'timeframe', 'date_as_of')
    )
    op.add_column('users', sa.Column('xp_current_season', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'xp_current_season')
    op.drop_table('xp_snapshot')
    # ### end Alembic commands ###
