"""Add credit_balance

Revision ID: 6f17321582e2
Revises: 32ac5b94ef75
Create Date: 2023-09-03 14:09:05.251776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f17321582e2'
down_revision = '32ac5b94ef75'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('credit_balance', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'credit_balance')
    # ### end Alembic commands ###
