"""update fields

Revision ID: 7eb0f0c43c4e
Revises: 13da1bec29e8
Create Date: 2024-06-15 13:44:58.732143

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7eb0f0c43c4e'
down_revision = '13da1bec29e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('cmc_rank', sa.Integer(), nullable=True, comment='coinmarketcap rank'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'cmc_rank')
    # ### end Alembic commands ###
