"""add token metrics

Revision ID: 805dd5ebe3da
Revises: 9f0b50554d2a
Create Date: 2024-06-15 00:37:23.238171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '805dd5ebe3da'
down_revision = '9f0b50554d2a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument_kpi_token_metrics',
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('market_cap', sa.Float(), server_default='0', nullable=False),
    sa.Column('real_market_cap', sa.Float(), server_default='0', nullable=False),
    sa.Column('holders', sa.Float(), server_default='0', nullable=False),
    sa.Column('risk_score', sa.Float(), server_default='0', nullable=False),
    sa.Column('liquidity', sa.Float(), server_default='0', nullable=False),
    sa.Column('number_markets', sa.Float(), server_default='0', nullable=False),
    sa.Column('date_as_of', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.id'], ),
    sa.PrimaryKeyConstraint('instrument_id')
    )
    op.alter_column('quiz_answers', 'is_correct',
               existing_type=sa.INTEGER(),
               comment='',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_answers', 'is_correct',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.drop_table('instrument_kpi_token_metrics')
    # ### end Alembic commands ###
