"""make email non-unique field

Revision ID: 888134e402fe
Revises: e3656c6a13bf
Create Date: 2023-01-03 19:37:59.059876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '888134e402fe'
down_revision = 'e3656c6a13bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_answers', 'is_correct',
               existing_type=sa.INTEGER(),
               comment='',
               existing_nullable=False)
    op.alter_column('skill_groups', 'group_key',
               existing_type=sa.VARCHAR(),
               comment='',
               existing_nullable=False)
    op.drop_constraint('users_email_key', 'users', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('skill_groups', 'group_key',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('quiz_answers', 'is_correct',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    # ### end Alembic commands ###
