"""add instrument status

Revision ID: 8a36671ed13c
Revises: 24d8942aea6d
Create Date: 2022-08-16 20:22:36.802178

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a36671ed13c'
down_revision = '24d8942aea6d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('status', sa.String(), server_default='active', nullable=False, comment='active, inactive, deleted'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'status')
    # ### end Alembic commands ###
