"""buy/sell transactions to be accompanied by a message

Revision ID: 907931a1a14c
Revises: f0033f8c1909
Create Date: 2024-08-15 11:34:32.365898

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '907931a1a14c'
down_revision = 'f0033f8c1909'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_transactions', sa.Column('message', sa.String(), nullable=True, comment='Message/comment left by the user'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_transactions', 'message')
    # ### end Alembic commands ###
