"""make kpi nullable

Revision ID: 971a48c6fd52
Revises: 7eb0f0c43c4e
Create Date: 2024-06-17 21:03:00.160104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '971a48c6fd52'
down_revision = '7eb0f0c43c4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instrument_kpi_token_metrics', 'market_cap',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('instrument_kpi_token_metrics', 'real_market_cap',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('instrument_kpi_token_metrics', 'holders',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('instrument_kpi_token_metrics', 'risk_score',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('instrument_kpi_token_metrics', 'liquidity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('instrument_kpi_token_metrics', 'number_markets',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'0'::double precision"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('instrument_kpi_token_metrics', 'number_markets',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('instrument_kpi_token_metrics', 'liquidity',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('instrument_kpi_token_metrics', 'risk_score',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('instrument_kpi_token_metrics', 'holders',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('instrument_kpi_token_metrics', 'real_market_cap',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    op.alter_column('instrument_kpi_token_metrics', 'market_cap',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False,
               existing_server_default=sa.text("'0'::double precision"))
    # ### end Alembic commands ###
