"""Add birdeye specific fields

Revision ID: 988901d35c24
Revises: d27af646f6e8
Create Date: 2024-06-13 18:25:18.856525

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '988901d35c24'
down_revision = 'd27af646f6e8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('token_chain', sa.String(), nullable=True, comment='token chain'))
    op.add_column('instruments', sa.Column('twitter_url', sa.String(), nullable=True, comment='token twitter url'))
    op.add_column('instruments', sa.Column('website_url', sa.String(), nullable=True, comment='token website url'))
    op.add_column('instruments', sa.Column('tg_url', sa.String(), nullable=True, comment='token telegram url'))
    op.add_column('instruments', sa.Column('discrod_url', sa.String(), nullable=True, comment='token discord url'))
    op.add_column('instruments', sa.Column('coingeckoId', sa.String(), nullable=True, comment='token coingecko id'))
    op.add_column('instruments', sa.Column('medium_url', sa.String(), nullable=True, comment='token medium url'))
    op.alter_column('instruments', 'token_address',
               existing_type=sa.VARCHAR(),
               comment='token contract address',
               existing_nullable=True)
    op.alter_column('quiz_answers', 'is_correct',
               existing_type=sa.INTEGER(),
               comment='',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_answers', 'is_correct',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('instruments', 'token_address',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='token contract address',
               existing_nullable=True)
    op.drop_column('instruments', 'medium_url')
    op.drop_column('instruments', 'coingeckoId')
    op.drop_column('instruments', 'discrod_url')
    op.drop_column('instruments', 'tg_url')
    op.drop_column('instruments', 'website_url')
    op.drop_column('instruments', 'twitter_url')
    op.drop_column('instruments', 'token_chain')
    # ### end Alembic commands ###
