"""use coingecko_id

Revision ID: 9f0b50554d2a
Revises: faffeedd00b0
Create Date: 2024-06-14 18:11:20.795352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f0b50554d2a'
down_revision = 'faffeedd00b0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('coingecko_id', sa.String(), nullable=True, comment='token coingecko id'))
    op.drop_column('instruments', 'coingeckoId')
    op.alter_column('quiz_answers', 'is_correct',
               existing_type=sa.INTEGER(),
               comment='',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_answers', 'is_correct',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.add_column('instruments', sa.Column('coingeckoId', sa.VARCHAR(), autoincrement=False, nullable=True, comment='token coingecko id'))
    op.drop_column('instruments', 'coingecko_id')
    # ### end Alembic commands ###
