"""extend instruments, set default values

Revision ID: a362e86f6ada
Revises: 7607f873c37c
Create Date: 2022-07-03 19:24:47.262719

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a362e86f6ada'
down_revision = '7607f873c37c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('subtitle', sa.String(), nullable=True, comment='2-3 word description of the instrument'))
    op.add_column('instruments', sa.Column('is_well_known', sa.Integer(), server_default='0', nullable=False, comment='1: tutorial friendly, 0: otherwise'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'is_well_known')
    op.drop_column('instruments', 'subtitle')
    # ### end Alembic commands ###
