"""add referrer_id

Revision ID: a7a701495247
Revises: 907931a1a14c
Create Date: 2024-08-19 21:59:34.852754

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7a701495247'
down_revision = '907931a1a14c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('referrer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'users', 'users', ['referrer_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'referrer_id')
    # ### end Alembic commands ###
