"""Remove ex_avg_price temporarily

Revision ID: a88513723e4c
Revises: 4312719407a2
Create Date: 2023-02-16 20:56:38.833727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a88513723e4c'
down_revision = '4312719407a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_transactions', 'ex_avg_price')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_transactions', sa.Column('ex_avg_price', sa.VARCHAR(), autoincrement=False, nullable=True, comment='Average price of the holding BEFORE the transaction has been executed'))
    # ### end Alembic commands ###
