"""Fix ex_avg_price type

Revision ID: bfc8dac7d9fd
Revises: a88513723e4c
Create Date: 2023-02-16 20:57:55.918416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfc8dac7d9fd'
down_revision = 'a88513723e4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio_transactions', sa.Column('ex_avg_price', sa.Float(), nullable=True, comment='Average price of the holding BEFORE the transaction has been executed'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio_transactions', 'ex_avg_price')
    # ### end Alembic commands ###
