"""add goals

Revision ID: c09b2ba29df0
Revises: 6f17321582e2
Create Date: 2023-09-21 20:53:12.844698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c09b2ba29df0'
down_revision = '6f17321582e2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('birth_year_estimated', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('dream_statement', sa.String(), nullable=True, comment='what is the dream of the user'))
    op.add_column('users', sa.Column('target_net_worth_long_term', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('commitment_level', sa.String(), nullable=True, comment='serious/casual'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'commitment_level')
    op.drop_column('users', 'target_net_worth_long_term')
    op.drop_column('users', 'dream_statement')
    op.drop_column('users', 'birth_year_estimated')
    # ### end Alembic commands ###
