"""added token address

Revision ID: d27af646f6e8
Revises: 00f06e5b0f67
Create Date: 2024-06-11 08:15:57.508215

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd27af646f6e8'
down_revision = '00f06e5b0f67'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('token_address', sa.String(), nullable=True))
    op.alter_column('quiz_answers', 'is_correct',
               existing_type=sa.INTEGER(),
               comment='',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_answers', 'is_correct',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.drop_column('instruments', 'token_address')
    # ### end Alembic commands ###
