"""add UserPushToken and PushReceipt

Revision ID: d8dd1944a0c0
Revises: aa3f4c13cd3f
Create Date: 2022-11-02 15:59:27.305698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8dd1944a0c0'
down_revision = 'aa3f4c13cd3f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_push_tokens',
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('date_last_validated', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('provider', 'token')
    )
    op.create_table('push_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('provider', sa.String(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('push_ticket_id', sa.String(), nullable=True),
    sa.Column('push_receipt_id', sa.String(), nullable=True),
    sa.Column('detail', sa.String(), nullable=True),
    sa.Column('date_sent', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_proxy_received', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_accepted', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['provider', 'token'], ['user_push_tokens.provider', 'user_push_tokens.token'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('quiz_answers', 'is_correct',
               existing_type=sa.INTEGER(),
               comment='',
               existing_nullable=False)
    op.alter_column('skill_groups', 'group_key',
               existing_type=sa.VARCHAR(),
               comment='',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skill_groups', 'group_key',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('quiz_answers', 'is_correct',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.drop_table('push_receipts')
    op.drop_table('user_push_tokens')
    # ### end Alembic commands ###
