"""add last_claimed

Revision ID: dbb5d9b69a9a
Revises: 8e23ab84229c
Create Date: 2022-11-09 20:44:27.451533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbb5d9b69a9a'
down_revision = '8e23ab84229c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('date_last_claimed_weekly_reward', sa.DateTime(timezone=True), nullable=True))
    op.add_column('portfolios', sa.Column('date_last_claimed_daily_reward', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('quiz_answers', 'is_correct',
               existing_type=sa.INTEGER(),
               comment='',
               existing_nullable=False)
    op.alter_column('skill_groups', 'group_key',
               existing_type=sa.VARCHAR(),
               comment='',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skill_groups', 'group_key',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('quiz_answers', 'is_correct',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.drop_column('portfolios', 'date_last_claimed_daily_reward')
    op.drop_column('portfolios', 'date_last_claimed_weekly_reward')
    # ### end Alembic commands ###
