"""skills and quizzes

Revision ID: e1d7c92775ab
Revises: 8a36671ed13c
Create Date: 2022-09-01 21:26:18.252386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e1d7c92775ab'
down_revision = '8a36671ed13c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_answers', 'is_correct',
               existing_type=sa.INTEGER(),
               comment='',
               existing_nullable=False)
    op.alter_column('skill_groups', 'group_key',
               existing_type=sa.VARCHAR(),
               comment='',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('skill_groups', 'group_key',
               existing_type=sa.VARCHAR(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.alter_column('quiz_answers', 'is_correct',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    # ### end Alembic commands ###
