"""add intraday reward

Revision ID: f0033f8c1909
Revises: 971a48c6fd52
Create Date: 2024-08-09 07:20:09.158968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0033f8c1909'
down_revision = '971a48c6fd52'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolios', sa.Column('date_last_claimed_intraday_reward', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolios', 'date_last_claimed_intraday_reward')
    # ### end Alembic commands ###
