"""fix type

Revision ID: faffeedd00b0
Revises: 988901d35c24
Create Date: 2024-06-13 19:50:36.257253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'faffeedd00b0'
down_revision = '988901d35c24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('discord_url', sa.String(), nullable=True, comment='token discord url'))
    op.drop_column('instruments', 'discrod_url')
    op.alter_column('quiz_answers', 'is_correct',
               existing_type=sa.INTEGER(),
               comment='',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('quiz_answers', 'is_correct',
               existing_type=sa.INTEGER(),
               comment=None,
               existing_comment='',
               existing_nullable=False)
    op.add_column('instruments', sa.Column('discrod_url', sa.VARCHAR(), autoincrement=False, nullable=True, comment='token discord url'))
    op.drop_column('instruments', 'discord_url')
    # ### end Alembic commands ###
